# Generated by Django 6.0.3 on 2026-04-06 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('mapa_sgb', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_secao', models.CharField(max_length=50, null=True, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Unidade superior (ex: Batalhão para um Posto)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subunidades', to='unidades.unidade')),
                ('tipo_servico', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'TIPO_POSTO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_por_servico', to='dictionaries.dictionary')),
                ('tipo_unidade', models.ForeignKey(limit_choices_to={'tipo': 'TIPO_UNIDADE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_por_nivel', to='dictionaries.dictionary')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('prefixo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('placa', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('opmcb', models.CharField(blank=True, max_length=100, null=True)),
                ('sgb', models.CharField(blank=True, max_length=50, null=True)),
                ('garagem', models.CharField(blank=True, max_length=100, null=True)),
                ('status_base', models.ForeignKey(limit_choices_to={'tipo': 'STATUS_VIATURA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaturas_por_status', to='dictionaries.dictionary')),
                ('tipo', models.ForeignKey(limit_choices_to={'tipo': 'TIPO_VIATURA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaturas_por_tipo', to='dictionaries.dictionary')),
                ('unidade_base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaturas_base', to='unidades.unidade')),
            ],
            options={
                'verbose_name': 'Viatura',
                'verbose_name_plural': 'Viaturas',
                'ordering': ['prefixo'],
            },
        ),
    ]
