# Generated by Django 6.0.3 on 2026-04-19 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_is_link_pending_and_more'),
        ('unidades', '0009_posto_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_change_pending',
            field=models.BooleanField(default=False, help_text='Define se há uma alteração de perfil aguardando aprovação'),
        ),
        migrations.AddField(
            model_name='user',
            name='requested_role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrador'), ('COBOM', 'Central (COBOM)'), ('BATALHAO', 'Batalhão (Total)'), ('SGB', 'SGB (Subgrupamento)'), ('POSTO', 'Posto Operacional')], help_text='Nova função solicitada', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='requested_unidade',
            field=models.ForeignKey(blank=True, help_text='Nova unidade solicitada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_vinculo', to='unidades.unidade'),
        ),
    ]
