# Generated by Django 6.0.3 on 2026-04-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Efetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('fonte', models.CharField(default='Google Sheets', max_length=100)),
                ('data_importacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Efetivo',
                'verbose_name_plural': 'Efetivos',
                'ordering': ['nome'],
            },
        ),
    ]
