# Generated by Django 6.0.3 on 2026-04-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0002_efetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='efetivo',
            name='mergulho',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='nome_do_pm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='ovb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='posto_secao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='re',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='sgb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
