# Generated by Django 6.0.3 on 2026-04-08 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0003_efetivo_mergulho_efetivo_nome_do_pm_efetivo_ovb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='mergulho',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ovb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='re',
            field=models.CharField(help_text='Formato: 000000-0', max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='O RE deve estar no formato 000000-0', regex='^\\d{6}-\\d{1}$')]),
        ),
    ]
