# Generated by Django 6.0.3 on 2026-04-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0004_funcionario_mergulho_funcionario_ovb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='efetivo',
            name='unidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
