# Generated by Django 6.0.3 on 2026-04-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0005_efetivo_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='efetivo',
            name='chave_posto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='dig',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='nome_guerra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='nome_padrao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='efetivo',
            name='telefone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
