# Generated by Django 6.0.3 on 2026-04-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0006_efetivo_chave_posto_efetivo_dig_efetivo_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
