# Generated by Django 6.0.3 on 2026-04-06 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '0001_initial'),
        ('efetivo', '0001_initial'),
        ('unidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapaDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapas_diarios', to='unidades.unidade')),
            ],
            options={
                'verbose_name': 'Mapa Diário',
                'verbose_name_plural': 'Mapas Diários',
                'ordering': ['-data', 'unidade'],
                'unique_together': {('data', 'unidade')},
            },
        ),
        migrations.CreateModel(
            name='AlocacaoViatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('status_no_dia', models.ForeignKey(limit_choices_to={'tipo': 'STATUS_VIATURA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.dictionary')),
                ('viatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidades.viatura')),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes_viaturas', to='escalas.mapadiario')),
            ],
            options={
                'verbose_name': 'Alocação de Viatura',
                'verbose_name_plural': 'Alocações de Viaturas',
                'unique_together': {('mapa', 'viatura')},
            },
        ),
        migrations.CreateModel(
            name='AlocacaoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.ForeignKey(help_text='Comandante, Motorista, Auxiliar, Supervisor, etc.', limit_choices_to={'tipo': 'FUNCAO_OPERACIONAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.dictionary')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efetivo.funcionario')),
                ('alocacao_viatura', models.ForeignKey(blank=True, help_text='Viatura na qual o funcionário está alocado. Se vazio, está avulso na unidade.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipe', to='escalas.alocacaoviatura')),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes_funcionarios', to='escalas.mapadiario')),
            ],
            options={
                'verbose_name': 'Alocação de Funcionário',
                'verbose_name_plural': 'Alocações de Funcionários',
                'unique_together': {('mapa', 'funcionario')},
            },
        ),
    ]
