# Generated by Django 6.0.3 on 2026-04-10 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0005_mapadiario_atualizado_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_acao', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('FINISH', 'Finalização')], max_length=10)),
                ('descricao', models.TextField()),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='escalas.mapadiario')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Alteração',
                'verbose_name_plural': 'Históricos de Alterações',
                'ordering': ['-data_hora'],
            },
        ),
    ]
