# Generated by Django 6.0.3 on 2026-04-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0008_alocacaofuncionario_inicio_servico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapadiario',
            name='periodo',
            field=models.CharField(blank=True, choices=[('dia', '06:45 às 19:00'), ('noite', '18:45 às 07:00')], max_length=10, null=True),
        ),
    ]
