# Generated by Django 6.0.3 on 2026-04-22 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em Andamento'), ('RESOLVIDO', 'Resolvido'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=20)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20)),
                ('categoria', models.CharField(choices=[('ERRO_SISTEMA', 'Erro de Sistema'), ('CORRECAO_DADOS', 'Correção de Dados'), ('DUVIDA', 'Dúvida'), ('SUGESTAO', 'Sugestão'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('requisitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Mensagem do Chamado',
                'verbose_name_plural': 'Mensagens do Chamado',
                'ordering': ['criado_em'],
            },
        ),
    ]
