# Generated by Django 6.0.3 on 2026-04-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='titulo',
            field=models.CharField(choices=[('ERRO_LOGIN', 'Dificuldade de Acesso / Login'), ('CORRECAO_EFETIVO', 'Correção de Dados do Efetivo'), ('VIATURA_INDISPONIVEL', 'Viatura não aparece no seletor'), ('ERRO_MAPA_FORCA', 'Erro ao salvar/finalizar Mapa'), ('SOLICITAR_UNIDADE', 'Cadastro de nova Unidade/Posto'), ('DUVIDA_SISTEMA', 'Dúvida sobre funcionalidade'), ('SUGESTAO_MELHORIA', 'Sugestão de Melhoria'), ('OUTRO', 'Outro Assunto')], max_length=100),
        ),
    ]
