# Generated by Django 6.0.3 on 2026-04-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_categoria_alter_ticket_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='lido_pelo_requisitante',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='lido_pelo_suporte',
            field=models.BooleanField(default=False),
        ),
    ]
