# Generated by Django 6.0.3 on 2026-04-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0002_unidade_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='viatura',
            name='fonte',
            field=models.CharField(default='Local', help_text='Origem do dado: Local ou Google Sheets', max_length=100),
        ),
    ]
