# Generated by Django 6.0.3 on 2026-04-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0005_alter_viatura_vol_agua'),
    ]

    operations = [
        migrations.AddField(
            model_name='viatura',
            name='combustivel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
