# Generated by Django 6.0.3 on 2026-04-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0006_viatura_combustivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viatura',
            name='placa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
