# Generated by Django 6.0.3 on 2026-04-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0007_alter_viatura_placa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('tipo_cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('area_km2', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('populacao', models.IntegerField(blank=True, null=True)),
                ('hab_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('bandeira', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('fonte', models.CharField(default='Google Sheets', max_length=100)),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('sgb', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_secao', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade_posto', models.CharField(blank=True, max_length=255, null=True)),
                ('operacional_adm', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco_quarte', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=100, null=True)),
                ('fonte', models.CharField(default='Google Sheets', max_length=100)),
                ('municipios', models.ManyToManyField(related_name='postos', to='unidades.municipio')),
            ],
            options={
                'verbose_name': 'Posto',
                'verbose_name_plural': 'Postos',
                'ordering': ['nome'],
            },
        ),
    ]
