# Generated by Django 6.0.3 on 2026-04-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0008_municipio_posto'),
    ]

    operations = [
        migrations.AddField(
            model_name='posto',
            name='unidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
