# Generated by Django 6.0.3 on 2026-04-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0006_historicoalteracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapadiario',
            name='equipe',
            field=models.CharField(blank=True, choices=[('A', 'Equipe A'), ('B', 'Equipe B'), ('C', 'Equipe C'), ('D', 'Equipe D'), ('E', 'Equipe E')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='mapadiario',
            name='prontidao',
            field=models.CharField(blank=True, choices=[('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARELA', 'Amarela')], max_length=10, null=True),
        ),
    ]
