# Generated by Django 6.0.3 on 2026-04-11 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('unidades', '0008_municipio_posto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_link_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='requested_role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrador'), ('BATALHAO', 'Batalhão (Total)'), ('SGB', 'SGB (Subgrupamento)'), ('POSTO', 'Posto Operacional')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='requested_unidades',
            field=models.ManyToManyField(blank=True, related_name='solicitacoes_vinculo', to='unidades.unidade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('BATALHAO', 'Batalhão (Total)'), ('SGB', 'SGB (Subgrupamento)'), ('POSTO', 'Posto Operacional')], default='POSTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='unidade',
            field=models.ForeignKey(blank=True, help_text='Unidade principal à qual este usuário pertence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='unidades.unidade'),
        ),
    ]
