# Generated by Django 6.0.3 on 2026-04-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_link_pending_user_requested_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_link_pending',
        ),
        migrations.RemoveField(
            model_name='user',
            name='requested_role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='requested_unidades',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COBOM', 'Central (COBOM)'), ('BATALHAO', 'Batalhão (Total)'), ('SGB', 'SGB (Subgrupamento)'), ('POSTO', 'Posto Operacional')], default='POSTO', max_length=20),
        ),
    ]
