# Generated by Django 6.0.3 on 2026-04-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Dicionário',
                'verbose_name_plural': 'Dicionários',
                'ordering': ['tipo', 'ordem', 'nome'],
                'unique_together': {('tipo', 'codigo')},
            },
        ),
    ]
