# Generated by Django 6.0.3 on 2026-04-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0003_viatura_fonte'),
    ]

    operations = [
        migrations.AddField(
            model_name='viatura',
            name='vol_agua',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
