# Generated by Django 6.0.3 on 2026-04-05 01:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('re', models.CharField(help_text='Formato: 000000-0', max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='O RE deve estar no formato 000000-0', regex='^\\d{6}-\\d{1}$')])),
                ('nome_completo', models.CharField(max_length=255)),
                ('nome_guerra', models.CharField(max_length=100)),
                ('posto_graduacao', models.ForeignKey(limit_choices_to={'tipo': 'POSTO_GRADUACAO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.dictionary')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['posto_graduacao__ordem', 'nome_completo'],
            },
        ),
    ]
