# Generated by Django 6.0.3 on 2026-04-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapadiario',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
