# Generated by Django 6.0.3 on 2026-04-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0002_mapadiario_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaofuncionario',
            name='dejem',
            field=models.BooleanField(default=False, verbose_name='DEJEM'),
        ),
    ]
