# Generated by Django 6.0.3 on 2026-04-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0003_alocacaofuncionario_dejem'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaofuncionario',
            name='inicio_dejem',
            field=models.TimeField(blank=True, null=True, verbose_name='Início DEJEM'),
        ),
        migrations.AddField(
            model_name='alocacaofuncionario',
            name='termino_dejem',
            field=models.TimeField(blank=True, null=True, verbose_name='Término DEJEM'),
        ),
    ]
