# Generated by Django 6.0.3 on 2026-04-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0004_alocacaofuncionario_inicio_dejem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapadiario',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
