# Generated by Django 6.0.3 on 2026-04-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0007_mapadiario_equipe_mapadiario_prontidao'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaofuncionario',
            name='inicio_servico',
            field=models.TimeField(blank=True, null=True, verbose_name='Início Serviço'),
        ),
        migrations.AddField(
            model_name='alocacaofuncionario',
            name='termino_servico',
            field=models.TimeField(blank=True, null=True, verbose_name='Término Serviço'),
        ),
    ]
