# Generated by Django 6.0.3 on 2026-04-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0009_mapadiario_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaofuncionario',
            name='sub_funcao',
            field=models.CharField(blank=True, choices=[('supervisor', 'Supervisor'), ('motorista', 'Motorista')], max_length=20, null=True),
        ),
    ]
