# Generated by Django 6.0.3 on 2026-04-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0010_alocacaofuncionario_sub_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaofuncionario',
            name='is_comandante_prontidao',
            field=models.BooleanField(default=False, verbose_name='Cmt Prontidão'),
        ),
    ]
