# Generated by Django 6.0.3 on 2026-04-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0011_alocacaofuncionario_is_comandante_prontidao'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaofuncionario',
            name='is_oficial_area',
            field=models.BooleanField(default=False, verbose_name='Oficial de Área'),
        ),
    ]
