# Generated by Django 6.0.3 on 2026-04-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_lido_pelo_requisitante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='protocolo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
